### ISSUE TITLE
Error on world Flights

### ISSUE THREAD

**Issue by vjeux** [senchalabs/philogl#11]
http://senchalabs.github.com/philogl/PhiloGL/examples/worldFlights/

Uncaught Error linking the shader: C:\Users\vjeux\AppData\Local\Google\Chrome\Application\13.0.782.1\Shader@0x04DDF408(154,17): warning X3206: implicit truncation of vector type
C:\Users\vjeux\AppData\Local\Google\Chrome\Application\13.0.782.1\Shader@0x04DDF408(89,5): warning X3565: loop simulation finished early, use /O1 or above for potentially better codegen
error X4507: maximum ps_3_0 constant register index (224) exceeded - Try reducing number of constants referenced

Stack Trace:
kPhiloGL.js:75
k.fromShaderSourcesPhiloGL.js:77
k.fromShaderURIs.g.onSuccess.g.onSuccessPhiloGL.js:78
u.send.h.onreadystatechangePhiloGL.js:80

**Comment by philogb** [comment]
Thanks for the info. - OS is Windows I suppose?

**Comment by vjeux** [comment]
Yes windows seven sorry i did not mention

**Comment by philogb** [comment]
I just fixed it and made a 1.2.1 version. The example should work now, but make sure you clear you browser's cache before running it :)

**Comment by vjeux** [comment]
Awesome it's working. Great job it looks really nice :)
